### ISSUE TITLE
BCM mode not working ?

### ISSUE THREAD

**Issue by pascalmartin** [JamesBarwell/rpi-gpio.js#11]
if i try gpio.setup with GPIO BCM 17 a receive this error "Channel 17 does not map to a GPIO pin

**Comment by johnmwright** [comment]
The issue is specific to GPIO 17, which has been omitted from the array in  getPinBcm()

**Comment by paviro** [comment]
GPIO 17 is still not working, any update on this? Same thing with GPIO  4.

**Comment by lnitram** [comment]
Seems that many GPIOs are not working in BCM mode on Raspberry PI 3.

**Comment by Franco-Poveda** [comment]
Error: Channel 20 does not map to a GPIO pin
Same problem.
raspberry pi 3.
Any way to fix this?

**Comment by Franco-Poveda** [comment]
A good fix is PR pending a a long time ago made: 
[https://github.com/JamesBarwell/rpi-gpio.js/pull/60
](https://github.com/JamesBarwell/rpi-gpio.js/pull/60


To use @jamesbulpin fork that fix this, change in your package.json rpi-gpio reference with:


`        "rpi-gpio": "git+ssh://git@github.com/jamesbulpin/rpi-gpio.js.git"
`

**Comment by JamesBarwell** [comment]
The fix in #60 has been published as `0.9.1`. Cheers.
