### ISSUE TITLE
WatchFile not working

### ISSUE THREAD

**Issue by Mrono** [JamesBarwell/rpi-gpio.js#2]
the on change event doesn't work, however I have traced the issue back to the fact that watchFile does not detect changes in the gpio files.  I managed to rig up a ghetto watcher by setInterval and comparing the values then calling a function, but that is bad.

Is there a fix/replacement for this?

**Comment by amalraj-nodejs** [comment]
I am trying to find a solution. I love this module and without change event working this module is useless. As far as I know hardware interruption doesn't change the mtime of file and fs.watchfile will not work. onoff uses epoll module in which requires python libraries which i don't like. Let's try to find a perfect solution and give you pull request.

**Comment by fivdi** [comment]
@amalraj-nodejs neither onoff nor epoll require python libraries, at least not directly. npm requires node-gyp for building the epoll addon and node-gyp in turn requires python.

**Comment by julienvincent** [comment]
>fs.watchFile doesn't get fired because the file never gets 'accessed' when setting header via hardware manually watching value changes.

This means that the fileWatcher within rpi-gpio.js will not fire an event after the initial read.

A fix for this is to watch for Interrupts generated by the GPIO chip. If you would like me to build this feature I will be happy to submit a pull request.

**Comment by JamesBarwell** [comment]
Resolved by #23
