### ISSUE TITLE
fs has no method 'exists' ?

### ISSUE THREAD

**Issue by GPrathap** [JamesBarwell/rpi-gpio.js#22]
This is the stack trace of error. 
/home/pi/node_modules/rpi-gpio/rpi-gpio.js:376
    fs.exists(PATH + '/gpio' + pin, function(exists) {
       ^
TypeError: Object #<Object> has no method 'exists'
    at isExported (/home/pi/node_modules/rpi-gpio/rpi-gpio.js:376:8)
    at /home/pi/node_modules/rpi-gpio/rpi-gpio.js:160:17
    at /home/pi/node_modules/rpi-gpio/node_modules/async/lib/async.js:641:34
    at Array.0 (/home/pi/node_modules/rpi-gpio/node_modules/async/lib/async.js:557:34)
    at EventEmitter._tickCallback (node.js:190:39)

**Comment by GPrathap** [comment]
I resolved this error after installing newest version of NodeJs (https://learn.adafruit.com/node-embedded-development/installing-node-dot-js)

**Comment by JamesBarwell** [comment]
Yes it sounds like a node version issue. Thanks for the link - I've updated the nodejs installation guidelines in the readme.
