### ISSUE TITLE
'gpio.on' binding not working on PI2

### ISSUE THREAD

**Issue by hadesara** [JamesBarwell/rpi-gpio.js#26]
I am trying out this library and I am not unable to follow the examples since the callback functions to gpio.on 'change' and 'export' are not being triggered. I notice that RPI2 is not mentioned anywhere on this repo. Do you support RPI2 ?

**Comment by julienvincent** [comment]
The RPi 2 is supported, however in the current master branch of this module, change listeners do not fire. We are busy implementing a new change listener which should be coming to master quite soon. So long you can use [my working fork](https://github.com/julienvincent/rpi-gpio.js) which is hardware tested and functioning.

**Comment by julienvincent** [comment]
This issue has been fixed.

**Comment by hadesara** [comment]
Awesome! Thank you. Referring to your latest comment, Is it merged into the repo's current master? Or do I still need to pick you fork?

**Comment by JamesBarwell** [comment]
Published today as 0.6.0, so just pull it in through npm.

**Comment by hadesara** [comment]
Sorry, haven't been able to test this yet. I will test it soon and provide feedback if any.

**Comment by hadesara** [comment]
Negative, Things seems to be broken 0.6.0. The change listeners do not work and even the callback read listener returns 'undefined'. Where as reverting to v0.5.2  has at least the callback read listeners works correctly.

**Comment by hadesara** [comment]
I take this back, the issue was with access permissions to /sys/class/gpio/gpio21/edge. Looks like all is well. Thank you for this update!

**Comment by julienvincent** [comment]
Ah yes this is something I intend to work on when I get time. Having to `sudo` run everything is impractical.
