### ISSUE TITLE
Mocha tests not running.

### ISSUE THREAD

**Issue by ShayD16** [JamesBarwell/rpi-gpio.js#56]
![image](https://cloud.githubusercontent.com/assets/12586319/24603737/a38493dc-187f-11e7-8a1d-d9d3776311ef.png)

**Comment by JamesBarwell** [comment]
I wouldn't expect this to work on Windows because the epoll module doesn't support it, and it is loaded during the tests. Can't think of any way around this other than to run it in a VM.

**Comment by ShayD16** [comment]
Ohh, I should have checked that. Thanks for the heads up. Will run the tests directly on the pi then.
