### ISSUE TITLE
Works great on Pi 3 B

### ISSUE THREAD

**Issue by prichardson** [JamesBarwell/rpi-gpio.js#70]
Note you must pass in  pin name not pin number. Other library I was using
took the GPIO name so I though it was not working at first... 

So GPIO 17 is # 11
gpio.setup(11,...);

**Comment by JamesBarwell** [comment]
Great, cheers for the feedback.

Yes, the pin numbering is very confusing and there are lots of outstanding issues around it which I hope to deal with soon.
