### ISSUE TITLE
'Could not locate bindings file' on Electron and Webpack

### ISSUE THREAD

**Issue by Catpants** [JamesBarwell/rpi-gpio.js#75]
I am running a project with electron and webpack which is [based on this project](https://medium.com/@Agro/developing-desktop-applications-with-electron-and-react-40d117d97564). However, whenever I run it, the following error appears.
```
Uncaught Error: Could not locate the bindings file.
Tried:
- /home/pi/build/epoll.node
- /home/pi/build/Debug/epoll.node
- /home/pi/build/Release/epoll.node
- /home/pi/out/Debug/epoll.node
...
```

**Comment by JamesBarwell** [comment]
Not sure as this looks to be an issue between epoll and Electron. Maybe this will help: https://github.com/fivdi/epoll/issues/22
