### ISSUE TITLE
How does one pass options like pull_up_down=io.PUD_UP

### ISSUE THREAD

**Issue by joseph-jja** [JamesBarwell/rpi-gpio.js#9]
I'm looking at taking advantage of the internal resistor:  https://learn.adafruit.com/adafruits-raspberry-pi-lesson-12-sensing-movement/software

Is there plan to support this?

**Comment by jurafa** [comment]
+1 for this request

**Comment by endotronic** [comment]
You can use device tree overlays to do this. https://www.raspberrypi.org/documentation/configuration/device-tree.md

**Comment by WalasPrime** [comment]
+1 for request, would be really useful

**Comment by JamesBarwell** [comment]
You can now export a pin as low or high in version `0.8.0`.

**Comment by adi1133** [comment]
@JamesBarwell can you go into more detail how this works ? I'd like to see a code snippet if possible.

**Comment by JamesBarwell** [comment]
It's the DIR_HIGH and DIR_LOW options to `setup`, which are mentioned in the README. Fair enough, yes the code samples could do with updating at some point, but I don't have time right now.

**Comment by adi1133** [comment]
Is DIR_HIGH the same as DIR_IN + pull up ?
Can you combine DIR_HIGH with interrupts ?

I will post a PR for the readme when I am sure I understand how this works.
