### ISSUE TITLE
gpio.setup error is not correctly caught by Promise

### ISSUE THREAD

**Issue by dawn-minion** [JamesBarwell/rpi-gpio.js#91]
If the regex match fails on [rpi-gpio.js:365](https://github.com/JamesBarwell/rpi-gpio.js/blob/master/rpi-gpio.js#L365), the next line that attempts access `match[1]` will fail and throw a TypeError that is not caught by the Promise. Instead of `.catch` being called and handling this in my promise, the program will die.

**Comment by JamesBarwell** [comment]
Thanks for reporting this and for the PR.

Out of interest, did you come across this using real Raspberry Pi hardware? Is there also an issue with the regex?

**Comment by dawn-minion** [comment]
@JamesBarwell Ah sorry, should have said here. Regex does seem fine, I just liked developing locally as it's quicker than on the Pi =)
