### ISSUE TITLE
when to support model 4?

### ISSUE THREAD

**Issue by spade69** [JamesBarwell/rpi-gpio.js#97]
Is there any plan to support raspberrry pi 4 model B?

**Comment by JamesBarwell** [comment]
I believe the GPIO layout hasn't changed so fingers crossed it just works. It really just needs someone to test it out and let us know. I don't have a 4 myself yet.

**Comment by spade69** [comment]
> I believe the GPIO layout hasn't changed so fingers crossed it just works. It really just needs someone to test it out and let us know. I don't have a 4 myself yet.

yet, i tried and it works, `write-pin.js` example works.
