### ISSUE TITLE
This library supported raspberry pi 4? 

### ISSUE THREAD

**Issue by psyrenpark** [JamesBarwell/rpi-gpio.js#98]
This library supported raspberry 4? 

I want use gpio library.

**Comment by JamesBarwell** [comment]
I expect it will work fine on the Pi 4, but I've not got one myself yet so haven't been able to confirm. If you have a chance to give it a test, please let us know. Cheers.

**Comment by Roaders** [comment]
I've tested on a raspberry pi 4 and it works fine.

**Comment by hartleyrobertson** [comment]
I can also confirm that it works on pi 4. Not sure if this is useful to anyone but no other version of NodeJs worked except for 10.20.1. Kept getting an install error relating to epoll.

**Comment by JamesBarwell** [comment]
Thanks for testing. I'll add it to the compatibility list. Not sure about the node version issue but we could get that raised as a separate issue.
